### ISSUE TITLE
Bi-level optimization

### ISSUE THREAD

**Issue by kleinzcy** [nayeemrizve/OpenLDN#1]
Hi, 

Thanks for your code. After reading your paper, I am curious about the bi-level optimization which in turn optimize \Phi, \Theta and \Omega. But in the code, I have not found any details of \Omega. Have you open-source the whole code or is there anything I miss?

Thanks.

**Comment by nayeemrizve** [comment]
Hello,

Thank you for expressing interest in our work. We have open-sourced the complete code. The optimization details of \Omega or similarity prediction network can be found in lines 247-270 of the https://github.com/nayeemrizve/OpenLDN/blob/main/base/train-base.py file. Hope this helps.

**Comment by devinxzhang** [comment]
Hi,

Thanks for your great work. I am also interested in the bi-level optimization. And I am a little bit confused of the motivation behind the pairwise similarity prediction network and the bi-level optimization.

In your paper, it is stated that the way to compute pairwise similarity loss in previous works, e.g., ORCA, is too expensive. Therefore, the pairwise similarity network is proposed to overcome this drawback.

I guess this referred to that for each feature embedding, the nearest embedding has to be found to construct the pair. This might be of low-efficiency. However, I cannot figure out why the pairwise similarity network is more efficient, since three forward operations has to be involved for looping one batch: one for optimizing the copied model, one for optimizing simnet, the last one for the model. This could also be of high-cost. 

Could you please tell me more about the advantage of the pairwise similarity network over ORCA? Thanks a lot!
